image: golang:1.13.4
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - make test
  branches:
    master:
      - step:
          name: test and build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - cd "${PACKAGE_PATH}"
            - make
            - go run -ldflags "-X main.version=${BITBUCKET_BRANCH} -X main.build=${BITBUCKET_BUILD_NUMBER}" main.go
            - go build  -v -o weos-controller -ldflags "-X main.version=${BITBUCKET_BRANCH} -X main.build=${BITBUCKET_BUILD_NUMBER}" main.go
            - chmod u+x weos-controller
            - chmod o+x weos-controller
            - tar -cvf weos-controller.latest.tar weos-controller
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" -F "files=@weos-controller.latest.tar"
            - cp weos-controller.latest.tar ${BITBUCKET_CLONE_DIR}
          artifacts:
            - weos-controller.latest.tar
    dev:
      - step:
          name: test and build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - cd "${PACKAGE_PATH}"
            - make
            - go run -ldflags "-X main.version=${BITBUCKET_BRANCH} -X main.build=${BITBUCKET_BUILD_NUMBER}" main.go
            - go build  -v -o weos-controller -ldflags "-X main.version=${BITBUCKET_BRANCH} -X main.build=${BITBUCKET_BUILD_NUMBER}" main.go
            - chmod u+x weos-controller
            - chmod o+x weos-controller
            - tar -cvf weos-controller.dev.tar weos-controller
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" -F "files=@weos-controller.dev.tar"
            - cp weos-controller.dev.tar ${BITBUCKET_CLONE_DIR}
          artifacts:
            - weos-controller.dev.tar
  tags:
    v*:
      - step:
          name: test and build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - cd "${PACKAGE_PATH}"
            - make
            - go run -ldflags "-X main.version=${BITBUCKET_TAG} -X main.build=${BITBUCKET_BUILD_NUMBER}" main.go
            - go build  -v -o weos-controller -ldflags "-X main.version=${BITBUCKET_TAG} -X main.build=${BITBUCKET_BUILD_NUMBER}" main.go
            - chmod u+x weos-controller
            - chmod o+x weos-controller
            - tar cvf weos-controller.${BITBUCKET_TAG}.tar weos-controller
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" -F "files=@weos-controller.${BITBUCKET_TAG}.tar"
            - cp weos-controller.${BITBUCKET_TAG}.tar ${BITBUCKET_CLONE_DIR}
          artifacts:
            - weos-contoller*
