image: golang:stretch
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - make
  branches:
    master:
      - step:
          name: test and build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - cd "${PACKAGE_PATH}"
            - make
            - tar -cvf weos-controller.latest.tar weos-controller
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" -F "files=@weos-controller.latest.tar"
            - cp weos-controller.latest.tar ${BITBUCKET_CLONE_DIR}
          artifacts:
            - weos-controller.latest.tar
  tags:
    WEOS*:
      - step:
          name: test and build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - cd "${PACKAGE_PATH}"
            - make
            - tar cvf weos-controller.${BITBUCKET_TAG}.tar weos-controller
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" -F "files=@weos-controller.${BITBUCKET_TAG}.tar"
            - cp weos-controller.${BITBUCKET_TAG}.tar ${BITBUCKET_CLONE_DIR}
          artifacts:
            - weos-controller*
    v*:
      - step:
          name: test and build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - cd "${PACKAGE_PATH}"
            - make
            - tar cvf weos-controller.${BITBUCKET_TAG}.tar weos-controller
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" -F "files=@weos-controller.${BITBUCKET_TAG}.tar"
            - cp weos-controller.${BITBUCKET_TAG}.tar ${BITBUCKET_CLONE_DIR}
          artifacts:
            - weos-contoller*
